version: '3'
services:
  nginx_server:
    build: ./NginxServer
    restart: always
    network_mode: host
    ports:
      - "80:80"

  mongo:
    image: mongo
    restart: always
    network_mode: host
    ports:
      - "27017:27017"

  server:
    build: ./Server
    network_mode: host
    ports:
      - "8888:8888"

  client:
    depends_on:
      - "server"
      - "nginx_server"
      - "mongo"
    build: ./Client
    network_mode: host
    ports:
      - "8080:8080"

  client1:
    depends_on:
      - "server"
      - "nginx_server"
      - "mongo"
    build: ./Client
    network_mode: host
    ports:
      - "8081:8081"
