version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./NginxServer/dist:/usr/share/nginx/html
    restart: always
    network_mode: host
    ports:
      - "80:80"

  mongo:
    image: mongo
    restart: always
    network_mode: host
    ports:
      - "27017:27017"

  server:
    build: ./Server
    network_mode: host
    ports:
      - "8888:8888"

  client:
    depends_on:
      - "server"
      - "nginx"
      - "mongo"
    build: ./Client
    network_mode: host
    ports:
      - "8081:8081"

  client1:
    depends_on:
      - "server"
      - "nginx"
      - "mongo"
    build: ./Client1
    network_mode: host
    ports:
      - "8081:8081"
